#!/bin/bash
KNI_NAME=$1
NS=$2
# Import common functions related to namespace operations
source /etc/128technology/plugins/network-scripts/common/namespace_helpers
source /etc/sysconfig/network-scripts/ifcfg-$1
source /etc/sysconfig/128T-squid-content-filter
LAST_OCTET=$(echo $IPADDR | cut -d '.' -f 4)
if [ $(($LAST_OCTET%2)) -eq 0 ]; then
  GATEWAY=$(echo $IPADDR | cut -d '.' -f 1-3).$(echo $(($LAST_OCTET - 1)))
else
  GATEWAY=$(echo $IPADDR | cut -d '.' -f 1-3).$(echo $(($LAST_OCTET + 1)))
fi

# create namespace if it doesn't exist
if [ ! -e "/var/run/netns/$SQUID_NAMESPACE" ]; then
  echo "$SQUID_NAMESPACE namespace does not exist...creating it."
  create_namespace $NS
  ip netns exec $SQUID_NAMESPACE ip link set lo up
  echo "$SQUID_NAMESPACE created."
fi

# set up KNI if it exists in the default namespace
if [ -d "/sys/devices/virtual/net/$KNI_NAME" ]; then
  echo "$KNI_NAME found in default namespace."
  echo "Moving $KNI_NAME to $SQUID_NAMESPACE namespace."
  ip link set $KNI_NAME netns $SQUID_NAMESPACE
  ip netns exec $SQUID_NAMESPACE ip a add $IPADDR/$PREFIX dev $KNI_NAME
  ip netns exec $SQUID_NAMESPACE ip l set $KNI_NAME up
  ip netns exec $SQUID_NAMESPACE ip r add default via $GATEWAY dev $KNI_NAME
fi

# start squid in the namespace
systemctl start 128t-squid-content-filter
systemctl start 128t-lighttpd-content-filter
